USE [master]
GO

/****** Object:  Database [PM01_121_Джуртубаев]    Script Date: 15.05.2025 12:56:46 ******/
CREATE DATABASE [PM01_121_Джуртубаев]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PM01_121_Джуртубаев', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PM01_121_Джуртубаев.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PM01_121_Джуртубаев_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PM01_121_Джуртубаев_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PM01_121_Джуртубаев].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET ARITHABORT OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET  MULTI_USER 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET QUERY_STORE = ON
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [PM01_121_Джуртубаев] SET  READ_WRITE 
GO


